name: CI

on: [ push, pull_request, release ]

jobs:
  static-analysis:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.2
